# This is only an example configuration file for the Hive CLI.

project_name: <change-me>
repo:
  url: https://github.com/hiverge/demo-project.git
  branch: main
  evaluation_script: evaluator.py
  evolve_files_and_ranges: main.py
sandbox:
  replicas: 3
  timeout: 1800
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"
    shmsize: "1Gi"
cloud_provider:
  gcp:
    enabled: true
