# This is only an example configuration file for the Hive CLI.

project_name: llm-speedrun
coordinator_config_name: default-coordinator-config
platform: k8s
repo:
  url: https://github.com/hiverge/llm-speedrun-project.git
  branch: main
  evaluation_script: cifar10-94-630/evaluator.py
  evolve_files_and_ranges: cifar10-94-630/main.py
sandbox:
  replicas: 3
  timeout: 1800
  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "2"
      memory: "2Gi"
    shmsize: "4Gi"
    accelerators: a100-40gb:1 # or a100-80gb:8 or h100:8
  pre_processor: |
    print("Running pre-processing script...")
  envs:
    - name: LOCK_SANDBOX
      value: "true"
dashboard:
  enabled: false
wandb:
  enabled: false
# cloud vendor configuration
cloud_provider:
  spot: true
  gcp:
    enabled: true
  aws:
    enabled: false
